[package]
name = "crasher"
version = "0.1.0"
edition = "2024"
authors = ["Qdrant Team"]

[dependencies]
anyhow = "1.0.104"
thiserror = "2.0.20"
chrono = "0.4.45"
rand = "0.10.2"
clap = { version = "4.6.6", features = ["derive"] }
futures = { version = "0.3.34", default-features = false, features = [
    "async-await",
    "std",
] }
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = { version = "0.1.19", default-features = false, features = [
    "fs",
] }
qdrant-client = "1.19.0"
ctrlc = "3.5.2"
log = "0.4.33"
env_logger = "0.11.11"
serde_json = "1.0.151"
uuid = { version = "1.24.1", features = ["v4", "serde"] }
tonic = "0.14.6"
reqwest = { version = "0.13.4", features = ["json"] } # for snapshot restore
ahash = "0.8.12"
nix = { version = "0.31.3", features = ["fs"] }

[lints]
workspace = true

[workspace.lints.clippy]
cast_lossless = "warn"
doc_link_with_quotes = "warn"
enum_glob_use = "warn"
explicit_into_iter_loop = "warn"
filter_map_next = "warn"
flat_map_option = "warn"
from_iter_instead_of_collect = "warn"
implicit_clone = "warn"
inconsistent_struct_constructor = "warn"
inefficient_to_string = "warn"
manual_is_variant_and = "warn"
manual_let_else = "warn"
needless_continue = "warn"
needless_raw_string_hashes = "warn"
ptr_as_ptr = "warn"
ref_option_ref = "warn"
uninlined_format_args = "warn"
unnecessary_wraps = "warn"
unused_self = "warn"
used_underscore_binding = "warn"
match_wildcard_for_single_variants = "warn"
needless_pass_by_ref_mut = "warn"
unused_async = "warn"
wildcard_enum_match_arm = "warn"

[profile.release]
lto = "fat"
codegen-units = 1
